[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10.0"
rand = "0.9.0"
argon2 = "0.5.3"
hex = "0.4.3"
rpassword = "7.3.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.70"